version: '3.8'
services:

  # Sticky Notes API
  stickynotescore.api:
    build:
      context: .
      dockerfile: StickyNotesCore.API/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - ConnectionStrings__StickyNotes=Server=db;Database=StickyNotes;User=sa;Password=pa$$w0rd123!*;TrustServerCertificate=true
      - CORS__ClientBaseAddress=http://localhost:5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # Sticky Notes UI
  stickynotescore.ui.blazor:
    build:
      context: .
      dockerfile: StickyNotesCore.UI.BlazorWebAssembly/Server/Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001

  # SQL Server Database
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - SA_PASSWORD=pa$$w0rd123!*
      - ACCEPT_EULA=Y